apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: beatrice
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes